#!/bin/sh
# Any copyright is dedicated to the Public Domain.
# http://creativecommons.org/publicdomain/zero/1.0/

[ "$1" = "x86" ] && flagsuf= || flagsuf=:x86-64
objdump -bbinary -mi386$flagsuf -Mintel -D /tmp/.rejit.dis | \
    awk '{ if(p){print;} } /<.data/{ p=1 }'
